### ISSUE TITLE
How to create grid view?

### ISSUE THREAD

**Issue by cemalsayin** [halilozel1903/AndroidTVMovieParadise#1]
Hi, i want to create a grid view for example how to show "top related" movies in grid view may it could be in another fragment. Is it possible?

**Comment by halilozel1903** [comment]
@cemalsayin Hello, Yes It's possible 
You can look this article: https://link.medium.com/vxcMWMZUZ9

**Comment by cemalsayin** [comment]
@halilozel1903 thanks for your answer.
