### ISSUE TITLE
Request Movie & TV Show

### ISSUE THREAD

**Issue by crak3rjack** [halilozel1903/AndroidTVMovieParadise#4]
Hi could it possible for you to make an Android TV app this website, has a great catalog and thanks.
https://goku.to/

**Comment by halilozel1903** [comment]
Hey, you can do it based on this project. 

Fyi @crak3rjack

**Comment by crak3rjack** [comment]
@halilozel1903 Sorry but I don't have a clientes on how to "noob" here, no knowledge of coding... just asking and thanks for quick response.🙂👋

**Comment by halilozel1903** [comment]
You can check this blog post : https://halilozel1903.medium.com/how-to-develop-android-tv-app-5e251f3aa56b 

Fyi. @crak3rjack
